python ./source/run_clm.py \
    --model_name_or_path nferruz/ProtGPT2 \
    --train_file ./data/processed/IPR035105.txt \
    --validation_file ./data/processed/IPR032724.txt \
    --tokenizer_name nferruz/ProtGPT2 \
    --do_train \
    --do_eval \
    --output_dir ./save/clm \
    --overwrite_output_dir \
    --learning_rate 1e-06  \
    --cache_dir ./cache